apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nodeport
  labels:
    app.kubernetes.io/instance: {{ .Release.Namespace }}
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: {{ .Values.service.nodePort }}
      protocol: "TCP"