apiVersion: v2
name: demo
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - demo

maintainers:
  - name : Pavlo Tsisar
    email: pavlo.tsisar@tattoo.courses
    url  : https://tattoo.courses