#  !!! Don't use for production !!!
apiVersion: v2
name       : postgres
description: Postgres Helm chart for Kubernetes
type       : application
version    : 0.1.0 # This is the Helm Chart version
appVersion : "latest" # This is the version of the application being deployed

keywords:
  - postgres

maintainers:
  - name : Pavlo Tsisar
    email: pavlo.tsisar@desynclabs.com
