apiVersion: v2
name       : proxy
description: Nginx proxy Helm chart for Kubernetes
type       : application
version    : 0.1.0   # This is the Helm Chart version
appVersion : "latest" # This is the version of the application being deployed

keywords:
  - proxy

maintainers:
  - name : Pavlo Tsisar
    email: pavlo.tsisar@desynclabs.com
